version: "3.9"

services:
  app:
    build: .
    container_name: homebase-app
    ports:
      - "3003:3003"
    environment:
      # This variable will be used inside app.js
      - MONGO_URL=mongodb://mongo:27017/homebase
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: homebase-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
